// Generated by https://quicktype.io

export type PokemonPaginatedResponse = {
  count: number;
  next: string;
  previous: null;
  results: Pokemon[];
};

export type Pokemon = {
  name: string;
  url: string;
};
export type SimplePokemon = {
  id: string;
  name: string;
  picture: string;
  color?: string;
};
